// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// invQ_r_Rcpp
arma::vec invQ_r_Rcpp(const arma::mat& cholQ, const arma::vec& r);
RcppExport SEXP _logitPQbound_invQ_r_Rcpp(SEXP cholQSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cholQ(cholQSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(invQ_r_Rcpp(cholQ, r));
    return rcpp_result_gen;
END_RCPP
}
// prjgrad_large_p
arma::vec prjgrad_large_p(arma::vec u, const arma::vec& y_nu, const arma::vec& nu_w, const arma::mat& xPxt_nu, const arma::mat& cholQ, double alpha, double thrs, int maxiter);
RcppExport SEXP _logitPQbound_prjgrad_large_p(SEXP uSEXP, SEXP y_nuSEXP, SEXP nu_wSEXP, SEXP xPxt_nuSEXP, SEXP cholQSEXP, SEXP alphaSEXP, SEXP thrsSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_nu(y_nuSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nu_w(nu_wSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xPxt_nu(xPxt_nuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cholQ(cholQSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type thrs(thrsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(prjgrad_large_p(u, y_nu, nu_w, xPxt_nu, cholQ, alpha, thrs, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// prjgrad_large_n
arma::vec prjgrad_large_n(arma::vec u, const arma::vec& y_nu, const arma::mat& nu_x, const arma::mat& cholQ, double alpha, double thrs, int maxiter);
RcppExport SEXP _logitPQbound_prjgrad_large_n(SEXP uSEXP, SEXP y_nuSEXP, SEXP nu_xSEXP, SEXP cholQSEXP, SEXP alphaSEXP, SEXP thrsSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_nu(y_nuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type nu_x(nu_xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cholQ(cholQSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type thrs(thrsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(prjgrad_large_n(u, y_nu, nu_x, cholQ, alpha, thrs, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// plogis
arma::vec plogis(arma::vec eta);
RcppExport SEXP _logitPQbound_plogis(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(plogis(eta));
    return rcpp_result_gen;
END_RCPP
}
// logpost
double logpost(arma::vec eta, arma::vec y, arma::vec beta, double alpha, double lambda);
RcppExport SEXP _logitPQbound_logpost(SEXP etaSEXP, SEXP ySEXP, SEXP betaSEXP, SEXP alphaSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(logpost(eta, y, beta, alpha, lambda));
    return rcpp_result_gen;
END_RCPP
}
// w_PG
arma::vec w_PG(arma::vec eta);
RcppExport SEXP _logitPQbound_w_PG(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(w_PG(eta));
    return rcpp_result_gen;
END_RCPP
}
// coeff_PQ
arma::vec coeff_PQ(arma::vec eta);
RcppExport SEXP _logitPQbound_coeff_PQ(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(coeff_PQ(eta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_logitPQbound_invQ_r_Rcpp", (DL_FUNC) &_logitPQbound_invQ_r_Rcpp, 2},
    {"_logitPQbound_prjgrad_large_p", (DL_FUNC) &_logitPQbound_prjgrad_large_p, 8},
    {"_logitPQbound_prjgrad_large_n", (DL_FUNC) &_logitPQbound_prjgrad_large_n, 7},
    {"_logitPQbound_plogis", (DL_FUNC) &_logitPQbound_plogis, 1},
    {"_logitPQbound_logpost", (DL_FUNC) &_logitPQbound_logpost, 5},
    {"_logitPQbound_w_PG", (DL_FUNC) &_logitPQbound_w_PG, 1},
    {"_logitPQbound_coeff_PQ", (DL_FUNC) &_logitPQbound_coeff_PQ, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_logitPQbound(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
