# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  accurate inverse-matrix vector product Q^{-1}r via Cholesky factorization
#'
#' @param cholQ the Cholesky factor of Q
#' @param r A vector
#'
#' @export
invQ_r_Rcpp <- function(cholQ, r) {
    .Call('_logitPQbound_invQ_r_Rcpp', PACKAGE = 'logitPQbound', cholQ, r)
}

#' projected gradient descent, optimized for large-p-small-n problems
#'
#' @param u (arma::vec(n)) initial solution
#' @param y_nu (arma::vec(n)) auxiliary vector 1
#' @param nu_w (arma::vec(n)) auxiliary vector 2
#' @param xPxt_nu (arma::mat(n,n)) auxiliary
#' @param cholQ (arma::mat(n,n)) auxiliary Cholesky matrix
#' @param alpha (double) gradient step size
#' @param thrs (double) stopping threshold on relative absolute change
#' @param maxiter (int) maximum number of iterations
#' 
#' @return logistic penalized log likelihood
#' 
#' @export
prjgrad_large_p <- function(u, y_nu, nu_w, xPxt_nu, cholQ, alpha, thrs, maxiter) {
    .Call('_logitPQbound_prjgrad_large_p', PACKAGE = 'logitPQbound', u, y_nu, nu_w, xPxt_nu, cholQ, alpha, thrs, maxiter)
}

#' projected gradient descent, optimized for large-n-small-p problems
#'
#' @param u (arma::vec(n)) initial solution
#' @param y_nu (arma::vec(n)) auxiliary vector
#' @param nu_x (arma::mat(n,p)) auxiliary matrix
#' @param cholQ (arma::mat(p,p)) auxiliary Cholesky matrix
#' @param alpha (double) gradient step size
#' @param thrs (double) stopping threshold on relative absolute change
#' @param maxiter (int) maximum number of iterations
#' 
#' @return logistic penalized log likelihood
#' 
#' @export
prjgrad_large_n <- function(u, y_nu, nu_x, cholQ, alpha, thrs, maxiter) {
    .Call('_logitPQbound_prjgrad_large_n', PACKAGE = 'logitPQbound', u, y_nu, nu_x, cholQ, alpha, thrs, maxiter)
}

#' inverse logit function
#'
#' @param eta (arma::vec(n)) linear predictors
#' 
#' @return inverse logit
#' 
#' @export
plogis <- function(eta) {
    .Call('_logitPQbound_plogis', PACKAGE = 'logitPQbound', eta)
}

#' logistic penalized log likelihood under elastic net regularization
#'
#' @param eta (arma::vec(n)) linear predictors
#' @param y (arma::vec(n)) responses
#' @param beta (arma::vec(p)) parameters (including intercept)
#' @param alpha (double) relative weight of L1 and L2 penalty
#' @param lambda (double) regularization parameter
#' 
#' @return logistic penalized log likelihood
#' 
#' @export
logpost <- function(eta, y, beta, alpha, lambda) {
    .Call('_logitPQbound_logpost', PACKAGE = 'logitPQbound', eta, y, beta, alpha, lambda)
}

#' PG bound coefficients
#'
#' @param eta (arma::vec(n)) linear predictors
#' 
#' @return PG weights
#' 
#' @export
w_PG <- function(eta) {
    .Call('_logitPQbound_w_PG', PACKAGE = 'logitPQbound', eta)
}

#' PQ bound coefficients
#'     Remark: correcting for numerical instability around 0
#'             numerical instability still present at Infinity  
#'
#' @param eta (arma::vec(n)) linear predictors
#' 
#' @return PQ w and nu (as an arma::vec(2*n))
#'
#' @export
coeff_PQ <- function(eta) {
    .Call('_logitPQbound_coeff_PQ', PACKAGE = 'logitPQbound', eta)
}

