# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' PG bound coefficients
#'
#' @param eta (arma::vec(n)) linear predictors
#' 
#' @return PG weights
#' 
#' @export
coeff_PG <- function(eta) {
    .Call(`_logitPQbound_coeff_PG`, eta)
}

#' PQ bound coefficients
#'     Remark: correcting for numerical instability around 0
#'             numerical instability still present at Infinity  
#'
#' @param eta (arma::vec(n)) linear predictors
#' 
#' @return PQ w and nu (as an arma::vec(2*n))
#'
#' @export
coeff_PQ <- function(eta) {
    .Call(`_logitPQbound_coeff_PQ`, eta)
}

#' ADMM optimizer for generalized lasso problems
#' 
#' @param x (arma::mat) design matrix.
#' @param y (arma::vec) response vector.
#' @param w (arma::vec) weight vector.
#' @param nu (arma::vec) penalty weight vector.
#' @param pL2 (arma::vec) ridge penalty vector.
#' @param beta0 (arma::vec) initial values.
#' @param lambda (double) generalized lasso penalty parameter.
#' @param rho (double) augmented Lagrangian penalty parameter.
#' @param objtol (double) objective function tollerance parameter.
#' @param reltol (double) relative tollerance parameter.
#' @param abstol (double) absolute tollerance parameter.
#' @param maxiter (int) maximum numner of iterations.
#' 
#' @return A list containing the estimated coefficients and the optimization history.
#' 
#' @export
admm_genlasso_PQ <- function(y, X, w, nu, pL2, beta0, lambda, rho, precondition, objtol, reltol, abstol, maxiter, history) {
    .Call(`_logitPQbound_admm_genlasso_PQ`, y, X, w, nu, pL2, beta0, lambda, rho, precondition, objtol, reltol, abstol, maxiter, history)
}

